###
## Copyright (2021) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, softaware
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####
---
  - name: Ensure previous docker is removed
    command: zypper remove -y docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine
    register: res
    failed_when: false

  - name: Ensure ports are free before installing controller.
    command: "{{ item }}"
    register: res
    failed_when: false
    with_items:
    - "pkill -9 epmd"
    - "pkill -9 httpd"
    - "pkill -9 haproxy"
    - "pkill -9 beam.smp"
    - "systemctl stop openvswitch"
    - "zypper remove -y openvswitch"
    - "systemctl stop kube-apiserver"
    - "systemctl stop etcd"

  - name: Check if common sles bin file is there
    find:
      paths: "/tmp/"
      use_regex: yes
      patterns: "common-cp-*"
      file_type: "file"
    register: var

  - name: Erase common sles release bin file
    shell: ./common-cp-* --erase
    when: var.files != []
    args:
      chdir: /tmp/

  - name: Disable swap
    command: swapoff -a
    tags: ['skip_ansible_lint']
