###
## Copyright (2020) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####
---
  - name: Get call to /api/v2/worker/k8shost to get k8shosts json response
    command: epicctl api get -u /api/v2/worker/k8shost -n {{ common.name }} -p "onprem" --jsonpath "._embedded.k8shosts" -o /tmp/get-response.json
    register: res
    failed_when: res.rc != 0
  
  - name: Check if response file exists.
    stat:
      path: /tmp/get-response.json
    register: output

  - name: Parse json to retrieve the tenant URI.
    set_fact:
      jsondata: "{{ lookup('file', '/tmp/get-response.json') | from_json }}"
    when: output.stat.exists == True

  - name: Store the host name from input.
    set_fact:
      k8s_host: "{{ item.host }}"     # here item refers to outer loop on pools
  
  - name: Set the k8s_host_uri variable.
    set_fact:
      k8s_host_uri: "{{ item._links.self.href }}"    # here item refers to json response array
    with_items: "{{ jsondata }}"
    when: item.ipaddr == k8s_host

  - debug:
      msg: "{{ k8s_host_uri }}"

  - name: set the k8s host role to variable
    set_fact:
      k8s_host_role: "{{ item.role }}"

  - name: Update k8shosts_config array in the json payload
    shell: cat /tmp/create_k8scluster.json | jq '.k8shosts_config |= . + [{{ item | to_json }}]' | tee /tmp/create_k8scluster.json
    with_template: k8shosts_config.j2
    vars:
      k8s_host_uri: "{{ k8s_host_uri }}"
      k8s_host_role: "{{ k8s_host_role }}"
  
