apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
data:
  dragent.yaml: |
    ### Agent tags
    # tags: linux:ubuntu,dept:dev,local:nyc

    #### Sysdig Software related config ####

    # Sysdig collector address
     collector: collector.sysdigcloud.com

    # Collector TCP port
     collector_port: <>

    # Whether collector accepts ssl
    # ssl: true

    # collector certificate validation
    # ssl_verify_certificate: false

    #######################################
     new_k8s: true
     k8s_cluster_name: <name of the cluster>
#    security:
#      k8s_audit_server_url: 0.0.0.0
#      k8s_audit_server_port: 7765
