###
## Copyright (2021) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####
---
# tasks file for tools

  - set_fact:
      env: {}
    when: common.proxy is not defined
  
  - set_fact:
      env:
        http_proxy: "{{ common.proxy.http }}"
        https_proxy: "{{ common.proxy.https }}"
        no_proxy: "{{ common.proxy.no_proxy }}"
    when: common.proxy is defined
  
  - name: Ensure directory is there for tools
    file:
      path: "{{ tools_dir }}"
      state: directory
    delegate_to: localhost

  - name: Start downloading tools
    get_url:
      url: " {{ item.url }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
      force: yes
    register: result
    until: result is succeeded
    retries: 30
    delay: 15 # Every 5 seconds
    with_items:
    - url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_cli_version }}/bin/linux/amd64/kubectl
      dest: "{{ tools_dir }}/kubectl"
      mode: 755
    - url: https://epicctl.s3.amazonaws.com/beta.6/linux/epicctl
      dest: "{{ tools_dir }}/epicctl"
      mode: 755
    - url: https://bluedata-releases.s3.amazonaws.com/kubectl-epic/3.2/162/linux/kubectl-hpecp
      dest: "{{ tools_dir }}/kubectl-hpecp"
      mode: 755
    - url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
      dest: "{{ tools_dir }}/jq"
      mode: 755
    environment: "{{ env }}"

  - name: Move epicctl to /usr/local/bin directory
    copy:
      src: "{{ tools_dir }}/epicctl"
      dest: /usr/local/bin
      mode: preserve
  
  - name: Move kubectl-hpecp to /usr/local/bin directory
    copy:
      src: "{{ tools_dir }}/kubectl-hpecp"
      dest: /usr/local/bin
      mode: preserve

  - name: Move kubectl to /usr/local/bin directory
    copy:
      src: "{{ tools_dir }}/kubectl"
      dest: /usr/local/bin
      mode: preserve

  - name: Move jq to /usr/local/bin directory
    copy:
      src: "{{ tools_dir }}/jq"
      dest: /usr/local/bin
      mode: preserve
