###
## Copyright (2021) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####


---

    - name: Create host file from input file
      command: python ./roles/os_deployment/tasks/create_hostfile.py '{{ servers | to_json}}'

    - name: Deploy image for each server and config using python method.
      command: python ./roles/os_deployment/tasks/python_method_handler.py image_deployment_ '{"server" :{{item | to_json}}, "config" :{{config | to_json}}}'
      register: image_deployment_output
      with_items: "{{ servers }}"
      async: 6000
      poll: 0
      loop_control:
        label: "{{ item.Server_serial_number }}"

    - name: Waiting for sles_os deployment to finish
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: _jobs
      until: _jobs.finished
      delay: 30
      retries: 100
      with_items: "{{ image_deployment_output.results }}"
      loop_control:
        label: "{{ item.ansible_job_id }}"

    - name: Print final output
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{_jobs.results}}"
      loop_control:
        label: "{{ item.ansible_job_id }}"


