---
  - name: creating payload json file 
    copy:
      dest: "/tmp/payload_ha.json"
      content: |
        {
          "clusterip": "{{ controllerha.clusterip }}",
          "cluster_dns_name": "{{ controllerha.cluster_dns_name }}",
          "shadow": "",
          "arbiter": "" 
        }
    register: output

  - debug:
      msg: "{{ output }}"