###
## Copyright (2021) Hewlett Packard Enterprise Development LP
##
## Licensed under the Apache License, Version 2.0 (the "License");
## You may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
####
---
  - name: Set the gateway ip variable
    set_fact:
      gateway_ip: "{{ item.gateway }}"

  - name: Set the gateway host variable
    set_fact:
      gateway_set_hostname: "{{ item.gateway_set_hostname }}"

  - name: Get session token for connecting to controller
    uri:
      url: http://{{ controller.host_ip }}:8080/api/v1/login
      return_content: yes
      validate_certs: false
      headers:
        Content-Type: "application/json"
        Accept-Charset: "UTF-8"
      method: POST
      body_format: json
      body: 
        name: "{{ controller_creds.name }}"
        password: "{{ controller_creds.password }}"
      status_code:
        - 201
    register: token

  - name: Fetch location header
    set_fact: 
      session_token="{{ token.location }}"
      
  - name: Fetch token 
    set_fact:
      token: "/{{session_token.split('/')[3]}}/{{session_token.split('/')[4]}}/{{session_token.split('/')[5]}}/{{session_token.split('/')[6]}}"

  - debug: 
      msg="{{ token }}"

  - name: Load add gateway payload json file
    include_vars:
      file: /tmp/payload_add_gateway.json
      name: add_gateway

  - name: Update ip in json file
    set_fact:
      add_gateway: "{{ add_gateway | default({}) | combine({ 'ip': gateway_ip }) }}"
  
  - name: Update hostname in json file
    set_fact:
      add_gateway: "{{ add_gateway | default({}) | combine({ 'proxy_nodes_hostname': gateway_set_hostname }) }}"

  - name: Write add-gateway file back to disk.
    copy:
      content: "{{ add_gateway | to_nice_json }}"
      dest: /tmp/payload_add_gateway.json

  - name: Add gateway nodes
    uri:
      url: http://{{ controller.host_ip }}:8080/api/v1/workers
      return_content: yes
      validate_certs: false
      headers:
        X-BDS-SESSION: "{{ token }}"
        Accept-Charset: "UTF-8"
      method: POST
      body_format: json
      body: "{{ lookup('file','/tmp/payload_add_gateway.json') }}"
      status_code:
        - 201
    register: res

  - debug:
      msg: "{{ res }}"

  - name: Sleep for 250 seconds and continue with play
    ansible.builtin.wait_for:
      timeout: 250

  - name: Get epic-workers info
    uri:
      url: http://{{ controller.host_ip }}:8080/api/v1/workers
      return_content: yes
      validate_certs: false
      headers:
        X-BDS-SESSION: "{{ token }}"
        Accept-Charset: "UTF-8"
        Content-Type: "application/json"
      method: GET
      status_code:
        - 200
    register: gateway_info

  - name: save the Json data to a Variable as a Fact
    set_fact:
      worker_info: "{{ gateway_info.content }}"

  - name: Get valid worker status
    set_fact:
      worker_hrefs_state: "{{ item.state}}"
    with_items: "{{worker_info._embedded.workers }}"
    when: item.ip == gateway_ip
  
  - debug: 
      msg: "gateway worker is ready"
    when: worker_hrefs_state == "installed"
  
  - debug:
      msg: "gateway worker adding is failed"
    failed_when: worker_hrefs_state == "prechecks_error" or worker_hrefs_state == "error"
    when: worker_hrefs_state != "installed"

